# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0008_auto_20160224_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='queue',
            field=models.CharField(default='default', help_text='e.g. urgent, background, etc.', max_length=100),
        ),
    ]
